name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Generate version info
      run: |
        VERSION=$(date +"%Y.%-m.%-d.%H%M")
        TIMESTAMP=$(date +%s)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        echo "Generated version: $VERSION"
        
    - name: Update version in files
      run: |
        # Update index.html
        sed -i "s/const buildVersion = '[^']*';/const buildVersion = '$VERSION';/g" TableClothLite/wwwroot/index.html
        
        # Update app.js
        sed -i "s/const buildVersion = '[^']*';/const buildVersion = '$VERSION';/g" TableClothLite/wwwroot/js/app.js
        
        # Update service-worker.js
        sed -i "s/const APP_VERSION = '[^']*';/const APP_VERSION = '$VERSION';/g" TableClothLite/wwwroot/service-worker.js
        sed -i "s/const BUILD_TIMESTAMP = [^;]*;/const BUILD_TIMESTAMP = $TIMESTAMP;/g" TableClothLite/wwwroot/service-worker.js
        
        # Update Chat.razor.cs
        sed -i 's/const string APP_VERSION = "[^"]*";/const string APP_VERSION = "'"$VERSION"'";/g' TableClothLite/Pages/Chat.razor.cs
        
        echo "Version updated in all files"
        
    - name: Restore dependencies
      run: dotnet restore TableClothLite/TableClothLite.csproj
      
    - name: Build
      run: dotnet build TableClothLite/TableClothLite.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish TableClothLite/TableClothLite.csproj --configuration Release --output ./publish
      
    - name: Create version.json
      run: |
        mkdir -p ./publish/wwwroot
        cat > ./publish/wwwroot/version.json << EOF
        {
          "version": "$VERSION",
          "timestamp": "$(date -Iseconds)",
          "buildTime": "$TIMESTAMP",
          "commit": "$GITHUB_SHA",
          "branch": "$GITHUB_REF_NAME"
        }
        EOF
        
    - name: Add smart cache headers
      run: |
        cat > ./publish/wwwroot/_headers << EOF
        # HTML 파일 - 항상 최신 버전 확인
        /*.html
          Cache-Control: no-cache, must-revalidate
          Pragma: no-cache
          X-Version: $VERSION
          X-Build-Time: $TIMESTAMP
        
        # 버전 정보 파일 - 캐시 방지
        /version.json
          Cache-Control: no-cache, no-store, must-revalidate
          Pragma: no-cache
          Expires: 0
        
        # Service Worker - 브라우저가 자동으로 24시간마다 체크
        /service-worker.js
          Cache-Control: public, max-age=0, must-revalidate
          X-Version: $VERSION
        
        # WASM 파일 - 해시 기반이므로 장기 캐시 가능
        *.wasm
        *.dll
        *.pdb
          Cache-Control: public, max-age=31536000, immutable
          X-Content-Type-Options: nosniff
        
        # JavaScript/CSS - ETag 기반 조건부 캐시
        *.js
        *.css
          Cache-Control: public, max-age=3600, must-revalidate
          X-Version: $VERSION
        
        # 이미지 및 폰트 - 중기 캐시
        *.png
        *.jpg
        *.jpeg
        *.gif
        *.ico
        *.woff
        *.woff2
          Cache-Control: public, max-age=86400, must-revalidate
        
        # JSON 파일 - 단기 캐시
        *.json
          Cache-Control: public, max-age=300, must-revalidate
          X-Version: $VERSION
        
        # Manifest 파일
        *.webmanifest
          Cache-Control: public, max-age=3600, must-revalidate
        EOF
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./publish/wwwroot

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4